app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  base-url:
    github: https://api.github.com/repos/
    stackoverflow: https://api.stackexchange.com/2.3/questions/
    bot: http://localhost:8090

spring:
  application:
    name: scrapper
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
