app:
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 100s
  base-url:
    github: https://api.github.com/repos/
    stackoverflow: https://api.stackexchange.com/2.3/questions/
    bot: http://localhost:8090
  db-access-type: jpa

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/scrapper
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
