global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: bot
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8093'

  - job_name: scrapper
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'host.docker.internal:8083'
