app:
  telegram-token: ${TOKEN}
  scrapper-url: "http://localhost:8080"
  retry-policy:
    codes: 500
    backoff: constant
    limit: 3
    delay: 5000

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
