/*
 * This file is generated by jOOQ.
 */

package edu.java.model.jooq;

import edu.java.model.jooq.tables.Chat;
import edu.java.model.jooq.tables.Databasechangeloglock;
import edu.java.model.jooq.tables.Link;
import edu.java.model.jooq.tables.Subscriptions;
import edu.java.model.jooq.tables.records.ChatRecord;
import edu.java.model.jooq.tables.records.DatabasechangeloglockRecord;
import edu.java.model.jooq.tables.records.LinkRecord;
import edu.java.model.jooq.tables.records.SubscriptionsRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CHAT_PKEY =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("chat_pkey"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(
        Databasechangeloglock.DATABASECHANGELOGLOCK,
        DSL.name("databasechangeloglock_pkey"),
        new TableField[] {Databasechangeloglock.DATABASECHANGELOGLOCK.ID},
        true
    );
    public static final UniqueKey<LinkRecord> LINK_PKEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_pkey"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> LINK_URL_KEY =
        Internal.createUniqueKey(Link.LINK, DSL.name("link_url_key"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<SubscriptionsRecord> SUBSCRIPTIONS_PKEY =
        Internal.createUniqueKey(Subscriptions.SUBSCRIPTIONS,
            DSL.name("subscriptions_pkey"),
            new TableField[] {Subscriptions.SUBSCRIPTIONS.ID},
            true
        );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SubscriptionsRecord, ChatRecord> SUBSCRIPTIONS__SUBSCRIPTIONS_CHAT_ID_FKEY =
        Internal.createForeignKey(Subscriptions.SUBSCRIPTIONS,
            DSL.name("subscriptions_chat_id_fkey"),
            new TableField[] {Subscriptions.SUBSCRIPTIONS.CHAT_ID},
            Keys.CHAT_PKEY,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<SubscriptionsRecord, LinkRecord> SUBSCRIPTIONS__SUBSCRIPTIONS_LINK_ID_FKEY =
        Internal.createForeignKey(Subscriptions.SUBSCRIPTIONS,
            DSL.name("subscriptions_link_id_fkey"),
            new TableField[] {Subscriptions.SUBSCRIPTIONS.LINK_ID},
            Keys.LINK_PKEY,
            new TableField[] {Link.LINK.ID},
            true
        );
}
