/*
 * This file is generated by jOOQ.
 */

package edu.java.model.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private OffsetDateTime visitedAt;
    private OffsetDateTime updatedAt;
    private Integer updatesCount;

    public Link() {
    }

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.visitedAt = value.visitedAt;
        this.updatedAt = value.updatedAt;
        this.updatesCount = value.updatesCount;
    }

    @ConstructorProperties({"id", "url", "visitedAt", "updatedAt", "updatesCount"})
    public Link(
        @Nullable Long id,
        @NotNull String url,
        @Nullable OffsetDateTime visitedAt,
        @Nullable OffsetDateTime updatedAt,
        @Nullable Integer updatesCount
    ) {
        this.id = id;
        this.url = url;
        this.visitedAt = visitedAt;
        this.updatedAt = updatedAt;
        this.updatesCount = updatesCount;
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 2048)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>public.link.visited_at</code>.
     */
    @Nullable
    public OffsetDateTime getVisitedAt() {
        return this.visitedAt;
    }

    /**
     * Setter for <code>public.link.visited_at</code>.
     */
    public void setVisitedAt(@Nullable OffsetDateTime visitedAt) {
        this.visitedAt = visitedAt;
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    @Nullable
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.link.updates_count</code>.
     */
    @Nullable
    public Integer getUpdatesCount() {
        return this.updatesCount;
    }

    /**
     * Setter for <code>public.link.updates_count</code>.
     */
    public void setUpdatesCount(@Nullable Integer updatesCount) {
        this.updatesCount = updatesCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.url == null) {
            if (other.url != null) {
                return false;
            }
        } else if (!this.url.equals(other.url)) {
            return false;
        }
        if (this.visitedAt == null) {
            if (other.visitedAt != null) {
                return false;
            }
        } else if (!this.visitedAt.equals(other.visitedAt)) {
            return false;
        }
        if (this.updatedAt == null) {
            if (other.updatedAt != null) {
                return false;
            }
        } else if (!this.updatedAt.equals(other.updatedAt)) {
            return false;
        }
        if (this.updatesCount == null) {
            if (other.updatesCount != null) {
                return false;
            }
        } else if (!this.updatesCount.equals(other.updatesCount)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.visitedAt == null) ? 0 : this.visitedAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.updatesCount == null) ? 0 : this.updatesCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(visitedAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatesCount);

        sb.append(")");
        return sb.toString();
    }
}
